import java.util.Vector;


/**
 *
 * @author oscargcervantes
 */
public class DisplayFrame extends javax.swing.JFrame
{
    private Vector<String> Elements;
	private Vector<String> Attributes;
    /** Creates new form DisplayFrame */
    public DisplayFrame(Vector<String> Elements, Vector<String> Attributes)
    {
        int i;
    	this.Elements = Elements;
        this.Attributes = Attributes;
    	initComponents();
    	DisplayJText.setText("");
    	for(i=0;i<Elements.size();i++)
    	{
    	  if(!Elements.elementAt(i).contentEquals("URL"))
    	  {	  
    		DisplayJText.append(Elements.elementAt(i) + " " + ":" + " " + Attributes.elementAt(i) + "\n");	
    	   }
    	 }	
     }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        DisplayJText = new javax.swing.JTextArea();
        DisplayLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        DisplayJText.setColumns(20);
        DisplayJText.setEditable(false);
        DisplayJText.setRows(5);
        jScrollPane1.setViewportView(DisplayJText);

        DisplayLabel.setText("Display video information");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DisplayLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(DisplayLabel)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea DisplayJText;
    private javax.swing.JLabel DisplayLabel;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
